version: "3.8"
services:
  client:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - /app/node_modules
      - ../../:/app

  jsonserver:
    restart: always
    build:
      context: ../../server
      dockerfile: Dockerfile

  nginx:
    depends_on:
      - client
    restart: always
    build:
      context: ../../nginx/dev
      dockerfile: Dockerfile
    ports:
      - 8080:80
